# Generated by Django 6.0.6 on 2026-06-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
    ]
