# Generated by Django 6.0.6 on 2026-07-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
